import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <title>Calembourama</title>
      </head>
      <body className="h-screen p-10 bg-primary-100 grid grid-rows-[auto_1fr] gap-4">
        <header>
          <h1 className="text-primary-800 text-3xl font-extrabold">
            Calembourama
          </h1>
        </header>

        <div className="bg-white rounded-2xl p-4">{children}</div>
      </body>
    </html>
  );
}
